vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        image:
            uri_prefix: /img
            upload_destination: '%kernel.project_dir%/public/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        photo:
            uri_prefix: /img
            upload_destination: '%kernel.project_dir%/public/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer